### ISSUE TITLE
Container does not start with long server names

### ISSUE THREAD

**Issue by PSanetra** [codecentric/single-page-application-server#6]
Starting a container with the following configuration will result in an error and terminate the container (see below).
```
default:
  spa_config: {}
special_server:
  server_names:
    - "very-long-subdomain-that-should-be-supported-by-default.example.com"
  spa_config:
    testProperty: "Special Server Value"
```

Nginx log:
```
2022/12/15 08:59:12 [emerg] 1#1: could not build server_names_hash, you should increase server_names_hash_bucket_size: 64
nginx: [emerg] could not build server_names_hash, you should increase server_names_hash_bucket_size: 64
```
